Repository projectcleanroom/clean_back, pull requests merged in 2024-09, with the labels that each got.

#112 feat : 이메일 인증 개발
  .idea/compiler.xml
  build.gradle
  src/main/java/com/clean/cleanroom/config/WebConfig.java
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/filter/JwtAuthenticationFilter.java
  src/main/java/com/clean/cleanroom/members/controller/MembersController.java
  src/main/java/com/clean/cleanroom/members/dto/EmailVerificationRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/VerifcationCodeRequestDto.java
  src/main/java/com/clean/cleanroom/members/entity/VerificationCode.java
  src/main/java/com/clean/cleanroom/members/repository/VerificationCodeRepository.java
  src/main/java/com/clean/cleanroom/members/service/EmailSenderService.java
  src/main/java/com/clean/cleanroom/members/service/MembersService.java
  src/main/resources/application.properties
Labels: feat

#114 refactor : 소셜로그인 응답에 redirect 경로 추가
  src/main/java/com/clean/cleanroom/members/controller/MembersLoginAndLogoutController.java
  src/main/java/com/clean/cleanroom/members/service/KakaoLoginService.java
  src/main/java/com/clean/cleanroom/members/service/MembersLoginService.java
Labels: refactor

#117 Refactor/social login
  .idea/compiler.xml
  src/main/java/com/clean/cleanroom/members/controller/MembersLoginAndLogoutController.java
  src/main/java/com/clean/cleanroom/members/service/KakaoLoginService.java
  src/main/java/com/clean/cleanroom/members/service/MembersLoginService.java
Labels: refactor

#119 Refactor/util
  .idea/dataSources.xml
  src/main/java/com/clean/cleanroom/account/service/AccountService.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/config/WebConfig.java
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
  src/main/java/com/clean/cleanroom/filter/JwtAuthenticationFilter.java
  src/main/java/com/clean/cleanroom/members/controller/MembersLoginAndLogoutController.java
  src/main/java/com/clean/cleanroom/members/entity/Members.java
  src/main/java/com/clean/cleanroom/members/service/MembersAddressService.java
  src/main/java/com/clean/cleanroom/members/service/MembersLoginService.java
  src/main/java/com/clean/cleanroom/members/service/MembersService.java
  src/main/java/com/clean/cleanroom/util/JwtUtil.java
  src/main/java/com/clean/cleanroom/util/TokenServiceImpl.java
Labels: refactor

#120 refactor : 스웨거 UI 스키마 설정
  src/main/java/com/clean/cleanroom/account/controller/AccountController.java
  src/main/java/com/clean/cleanroom/account/dto/AccountRequestDto.java
  src/main/java/com/clean/cleanroom/account/entity/Account.java
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCancelResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmDetailResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCreateRequestDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCreateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionFileGetResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionFileResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionUpdateRequestDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/MyCommissionResponseDto.java
  src/main/java/com/clean/cleanroom/config/SwaggerConfig.java
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateDetailResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateResponseDto.java
  src/main/java/com/clean/cleanroom/members/controller/MembersAddressController.java
  src/main/java/com/clean/cleanroom/members/controller/MembersController.java
  src/main/java/com/clean/cleanroom/members/controller/MembersLoginController.java
  src/main/java/com/clean/cleanroom/members/dto/EmailVerificationRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/KakaoAuthCodeRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/KakaoUserInfoRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/MemberIdAndNickDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressDelResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersEmailAndPasswordDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersGetProfileResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersLoginRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersLoginResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersLogoutResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersProfileResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersSignupRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersSignupResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersUpdateProfileRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/OAuthTokenDto.java
  src/main/java/com/clean/cleanroom/members/dto/VerifcationCodeRequestDto.java
  src/main/java/com/clean/cleanroom/members/service/MembersLoginService.java
  src/main/resources/application.properties
Labels: refactor

#121 refactor : config 주소 수정
  src/main/java/com/clean/cleanroom/config/SwaggerConfig.java
Labels: refactor

#122 refactor : redis를 활용하여 이메일 인증 코드 관리
  .idea/dataSources.xml
  build.gradle
  src/main/java/com/clean/cleanroom/config/RedisConfig.java
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/exception/GlobalExceptionHandler.java
  src/main/java/com/clean/cleanroom/exception/UnAuthenticationException.java
  src/main/java/com/clean/cleanroom/members/service/MembersService.java
  src/main/java/com/clean/cleanroom/redis/RedisService.java
  src/main/java/com/clean/cleanroom/util/ResponseDto.java
  src/main/resources/application.properties
Labels: refactor

#123 Feat : 성능태스트 개선 redis 활용한 조회로직에 캐시 적용
  build.gradle
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/config/RedisConfig.java
  src/main/java/com/clean/cleanroom/exception/GlobalExceptionHandler.java
  src/main/java/com/clean/cleanroom/exception/UnAuthenticationException.java
  src/main/java/com/clean/cleanroom/redis/RedisService.java
Labels: feat

#127 Feat/payment
  .idea/dataSources.xml
  .idea/jarRepositories.xml
  build.gradle
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/config/PortOneConfig.java
  src/main/java/com/clean/cleanroom/enums/PayMethod.java
  src/main/java/com/clean/cleanroom/enums/PaymentStatusType.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/exception/GlobalExceptionHandler.java
  src/main/java/com/clean/cleanroom/exception/InvalidQuoteException.java
  src/main/java/com/clean/cleanroom/exception/QuoteNotFoundException.java
  src/main/java/com/clean/cleanroom/filter/JwtAuthenticationFilter.java
  src/main/java/com/clean/cleanroom/payment/controller/PaymentController.java
  src/main/java/com/clean/cleanroom/payment/dto/CancelPaymentRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/CancelPaymentResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/EstimateAndCommissionResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentDetailRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentDetailResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentPrepareRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentPrepareResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PortOneTokenRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PortOneTokenResponseDto.java
  src/main/java/com/clean/cleanroom/payment/entity/PaymentEntity.java
  src/main/java/com/clean/cleanroom/payment/repository/PaymentRepository.java
  src/main/java/com/clean/cleanroom/payment/service/PaymentService.java
  src/main/java/com/clean/cleanroom/payment/service/PortOneService.java
  src/main/java/com/clean/cleanroom/util/ResponseDto.java
  src/main/resources/application.properties
  src/test/java/com/clean/cleanroom/account/controller/AccountControllerTest.java
  src/test/java/com/clean/cleanroom/account/dto/AccountRequestDtoTest.java
  src/test/java/com/clean/cleanroom/account/dto/MessageResponseDtoTest.java
  src/test/java/com/clean/cleanroom/account/entity/AccountTest.java
  src/test/java/com/clean/cleanroom/account/service/AccountServiceTest.java
  src/test/java/com/clean/cleanroom/commission/service/CommissionServiceTest.java
  src/test/java/com/clean/cleanroom/estimate/controller/EstimateControllerTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/entity/EstimateTest.java
  src/test/java/com/clean/cleanroom/estimate/service/EstimateServiceTest.java
Labels: feat

#128 refactor : Redis 직렬화문제 해결
  src/main/java/com/clean/cleanroom/config/RedisConfig.java
  src/main/java/com/clean/cleanroom/redis/RedisService.java
Labels: refactor

#129 refactor : Redis 직렬화문제 해결 주석 삭제
  src/main/java/com/clean/cleanroom/config/RedisConfig.java
  src/main/java/com/clean/cleanroom/redis/RedisService.java
Labels: refactor

#130 refactor : 스네이크케이스를 카멜케이스로 변경
  src/main/java/com/clean/cleanroom/payment/dto/CancelPaymentRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/CancelPaymentResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/EstimateAndCommissionResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentDetailRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentDetailResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentPrepareRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentPrepareResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PaymentResponseDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PortOneTokenRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PortOneTokenResponseDto.java
  src/main/java/com/clean/cleanroom/payment/entity/PaymentEntity.java
  src/main/java/com/clean/cleanroom/payment/repository/PaymentRepository.java
  src/main/java/com/clean/cleanroom/payment/service/PaymentService.java
Labels: refactor

#131 Test/ 단위 테스트 코드 추가
  build.gradle
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/test/java/com/clean/cleanroom/account/controller/AccountControllerTest.java
  src/test/java/com/clean/cleanroom/commission/controller/CommissionControllerTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionCancelResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionConfirmDetailResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionCreateRequestDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionCreateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionUpdateRequestDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionUpdateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/MyCommissionResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/entity/CommissionTest.java
  src/test/java/com/clean/cleanroom/commission/service/CommissionServiceTest.java
  src/test/java/com/clean/cleanroom/estimate/controller/EstimateControllerTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateDetailResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/entity/EstimateTest.java
  src/test/java/com/clean/cleanroom/estimate/service/EstimateServiceTest.java
  src/test/java/com/clean/cleanroom/exception/CustomExceptionTest.java
  src/test/java/com/clean/cleanroom/exception/GlobalExceptionHandlerTest.java
  src/test/java/com/clean/cleanroom/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/clean/cleanroom/jwt/RefreshTokenEntityTest.java
  src/test/java/com/clean/cleanroom/jwt/TokenResponseDtoTest.java
  src/test/java/com/clean/cleanroom/jwt/TokenServiceTest.java
  src/test/java/com/clean/cleanroom/members/controller/MembersAddressControllerTest.java
  src/test/java/com/clean/cleanroom/members/controller/MembersControllerTest.java
  src/test/java/com/clean/cleanroom/members/controller/MembersLoginControllerTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersAddressDelResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersAddressRequestDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersAddressResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersGetProfileResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersLoginRequestDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersLoginResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersProfileResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersSignupRequestDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersSignupResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersUpdateProfileRequestDtoTest.java
  src/test/java/com/clean/cleanroom/members/entity/AddressTest.java
  src/test/java/com/clean/cleanroom/members/entity/MembersTest.java
  src/test/java/com/clean/cleanroom/members/service/MembersAddressServiceTest.java
  src/test/java/com/clean/cleanroom/members/service/MembersLoginServiceTest.java
  src/test/java/com/clean/cleanroom/members/service/MembersServiceTest.java
  src/test/java/com/clean/cleanroom/util/JwtUtilTest.java
  src/test/java/com/clean/cleanroom/util/TokenServiceImplTest.java
Labels: test

#132 Refactor : 포트원 결제 토큰 로직 수정
  .idea/dataSources.xml
  src/main/java/com/clean/cleanroom/config/AppConfig.java
  src/main/java/com/clean/cleanroom/config/PortOneConfig.java
  src/main/java/com/clean/cleanroom/payment/controller/PaymentController.java
  src/main/java/com/clean/cleanroom/payment/dto/PortOneTokenRequestDto.java
  src/main/java/com/clean/cleanroom/payment/dto/PortOneTokenResponseDto.java
  src/main/java/com/clean/cleanroom/payment/service/PaymentService.java
  src/main/java/com/clean/cleanroom/payment/service/PortOneService.java
Labels: refactor
