Repository projectcleanroom/clean_back, pull requests merged in 2024-08, with the labels that each got.

#27 feat : validation 전화번호 '-' 제거
  src/main/java/com/clean/cleanroom/members/dto/MembersRequestDto.java
Labels: feat

#29 refactor : Custom Exception 보안적 위반사례 검토
  src/main/java/com/clean/cleanroom/exception/CustomException.java
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/exception/GlobalExceptionHandler.java
  src/main/java/com/clean/cleanroom/filter/JwtAuthenticationFilter.java
  src/main/java/com/clean/cleanroom/members/controller/MembersLoginAndLogoutController.java
  src/main/java/com/clean/cleanroom/members/service/MembersLoginService.java
  src/main/java/com/clean/cleanroom/util/JwtUtil.java
  src/main/java/com/clean/cleanroom/util/ResponseDto.java
Labels: refactor

#31 bug : 민감정보 숨김처리
  src/main/resources/application-blue.properties
  src/main/resources/application-green.properties
  src/main/resources/application.properties
Labels: bug

#33 feat : getProfile 생성 및 에러처리 적용
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/members/controller/MembersController.java
  src/main/java/com/clean/cleanroom/members/dto/MembersGetProfileResponseDto.java
  src/main/java/com/clean/cleanroom/members/repository/MembersRepository.java
  src/main/java/com/clean/cleanroom/members/service/MembersService.java
  src/main/resources/application.properties
Labels: feat

#35 feat : logback-spring.xml 로컬 로깅 추가
  build.gradle
  src/main/resources/logback-spring.xml
Labels: feat

#36 refactor : 견적 승인 API 수정
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
  src/test/java/com/clean/cleanroom/CleanRoomApplicationTests.java
  src/test/java/com/clean/cleanroom/commission/controller/CommissionControllerTest.java
  src/test/java/com/clean/cleanroom/commission/service/CommissionServiceTest.java
  src/test/java/com/clean/cleanroom/estimate/service/EstimateServiceTest.java
  src/test/java/com/clean/cleanroom/members/controller/MembersLoginAndLogoutControllerTest.java
  src/test/java/com/clean/cleanroom/members/service/MembersLoginServiceTest.java
Labels: refactor

#37 refactor : HouseType enums 수정
  src/main/java/com/clean/cleanroom/enums/HouseType.java
Labels: refactor

#38 refactor : type nmae 수정
  .idea/modules.xml
  .idea/modules/cleanRoom.main.iml
  src/main/java/com/clean/cleanroom/enums/CleanType.java
Labels: refactor

#40 bug : 회원가입 에러처리
  .idea/compiler.xml
  .idea/modules.xml
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/members/service/MembersService.java
  src/main/resources/application.properties
Labels: bug

#39 feat : INFO 레벨 로그와 ERRROR레벨 로그를 파일로 저장.
  src/main/resources/logback-spring.xml
Labels: feat

#41 refactor : 환경별로 로그 전략을 분리
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: refactor

#42 feat : 주소API 생성
  src/main/java/com/clean/cleanroom/members/controller/MembersAddressController.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressResponseDto.java
  src/main/java/com/clean/cleanroom/members/entity/Address.java
  src/main/java/com/clean/cleanroom/members/entity/Members.java
  src/main/java/com/clean/cleanroom/members/repository/AddressRepository.java
  src/main/java/com/clean/cleanroom/members/service/MembersAddressService.java
Labels: feat

#44 refactor : 개발환경 로그설정 변경 (ERROR레벨 -> INFO 레벨)
  src/main/resources/logback-spring.xml
Labels: refactor

#46 hotfix : https 요청경로 추가
  src/main/java/com/clean/cleanroom/config/SwaggerConfig.java
Labels: hotfix

#47 rename : members Comment add
  src/main/java/com/clean/cleanroom/members/entity/Address.java
  src/main/java/com/clean/cleanroom/members/entity/Members.java
Labels: rename

#49 Test : estimate test code
  src/test/java/com/clean/cleanroom/estimate/controller/EstimateControllerTest.java
  src/test/java/com/clean/cleanroom/estimate/service/EstimateServiceTest.java
Labels: test

#50 refactor : entity 코멘트 어노테이션 추가
  src/main/java/com/clean/cleanroom/account/entity/Account.java
  src/main/java/com/clean/cleanroom/business/entity/BusinessInfo.java
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
Labels: refactor

#52 remove : 사업자 도메인 삭제(파트너 서버로 옮깁니다)
  src/main/java/com/clean/cleanroom/business/controller/BusinessInfoController.java
  src/main/java/com/clean/cleanroom/business/dto/BusinessInfoRequestDto.java
  src/main/java/com/clean/cleanroom/business/dto/BusinessInfoResponseDto.java
  src/main/java/com/clean/cleanroom/business/dto/BusinessInfoUpdateRequestDto.java
  src/main/java/com/clean/cleanroom/business/dto/BusinessInfoUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/business/entity/BusinessInfo.java
  src/main/java/com/clean/cleanroom/business/repository/BusinessInfoRepository.java
  src/main/java/com/clean/cleanroom/business/service/BusinessInfoService.java
  src/main/java/com/clean/cleanroom/members/entity/Members.java
Labels: remove

#53 refactor : address 타입 수정
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCancelResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCreateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/MyCommissionResponseDto.java
Labels: refactor

#54 refactor : 하우스 타입 enums 수정
  src/main/java/com/clean/cleanroom/enums/HouseType.java
Labels: refactor

#56 Fix : commission 청소의뢰가 삭제될때 연관된 청소견적들이 사라지도록 종속성 전이 수정
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
Labels: fix

#57 refector : passwd 변경 로직
  src/main/java/com/clean/cleanroom/members/service/MembersService.java
  src/main/resources/application.properties
Labels: refactor

#58 refector : passwd 변경 로직
  src/main/resources/application.properties
Labels: refactor

#59 refector : passwd ëlogin midify
  src/main/java/com/clean/cleanroom/members/controller/MembersController.java
  src/main/java/com/clean/cleanroom/members/dto/MembersUpdateProfileRequestDto.java
  src/main/java/com/clean/cleanroom/members/entity/Members.java
  src/main/java/com/clean/cleanroom/members/service/MembersService.java
Labels: refactor

#60 Test/estimate
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/entity/EstimateTest.java
  src/test/java/com/clean/cleanroom/estimate/service/EstimateServiceTest.java
Labels: test

#61 test : account 패키지 테스트 코드 추가
  src/test/java/com/clean/cleanroom/account/controller/AccountControllerTest.java
  src/test/java/com/clean/cleanroom/account/dto/AccountRequestDtoTest.java
  src/test/java/com/clean/cleanroom/account/dto/MessageResponseDtoTest.java
  src/test/java/com/clean/cleanroom/account/entity/AccountTest.java
  src/test/java/com/clean/cleanroom/account/service/AccountServiceTest.java
Labels: test

#63 refactor : address Del API add
  src/main/java/com/clean/cleanroom/members/controller/MembersAddressController.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressDelResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressResponseDto.java
  src/main/java/com/clean/cleanroom/members/repository/AddressRepository.java
  src/main/java/com/clean/cleanroom/members/service/MembersAddressService.java
Labels: refactor

#64 Test/commission
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/main/java/com/clean/cleanroom/members/controller/MembersAddressController.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressDelResponseDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressRequestDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersAddressResponseDto.java
  src/main/java/com/clean/cleanroom/members/entity/Address.java
  src/main/java/com/clean/cleanroom/members/repository/AddressRepository.java
  src/main/java/com/clean/cleanroom/members/service/MembersAddressService.java
  src/test/java/com/clean/cleanroom/account/controller/AccountControllerTest.java
  src/test/java/com/clean/cleanroom/account/dto/AccountRequestDtoTest.java
  src/test/java/com/clean/cleanroom/account/dto/MessageResponseDtoTest.java
  src/test/java/com/clean/cleanroom/account/entity/AccountTest.java
  src/test/java/com/clean/cleanroom/account/service/AccountServiceTest.java
  src/test/java/com/clean/cleanroom/commission/controller/CommissionControllerTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionCancelResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionCreateRequestDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionCreateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionUpdateRequestDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/CommissionUpdateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/dto/MyCommissionResponseDtoTest.java
  src/test/java/com/clean/cleanroom/commission/entity/CommissionTest.java
  src/test/java/com/clean/cleanroom/commission/service/CommissionServiceTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/entity/EstimateTest.java
  src/test/java/com/clean/cleanroom/estimate/service/EstimateServiceTest.java
Labels: refactor, test

#65 test : exception 테스트 코드 추가
  src/test/java/com/clean/cleanroom/exception/CustomExceptionTest.java
  src/test/java/com/clean/cleanroom/exception/GlobalExceptionHandlerTest.java
Labels: test

#66 feat : 견적을 받은 청소 의뢰 리스트 조회
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionUpdateRequestDto.java
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/commission/repository/CommissionRepository.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/enums/PartnerType.java
  src/main/java/com/clean/cleanroom/enums/StatusType.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateResponseDto.java
  src/main/java/com/clean/cleanroom/partner/entity/Partner.java
Labels: feat, refactor

#67 refactor : 청소의뢰 작성시 기본상태를 반환하도록 추가
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCreateResponseDto.java
Labels: refactor

#68 Feat/commission get
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmDetailResponseDto.java
  src/main/java/com/clean/cleanroom/commission/repository/CommissionRepository.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/estimate/entity/Estimate.java
  src/test/java/com/clean/cleanroom/estimate/controller/EstimateControllerTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateListResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/entity/EstimateTest.java
  src/test/java/com/clean/cleanroom/estimate/service/EstimateServiceTest.java
Labels: feat

#70 refactor : CommissionConfirmListResponseDto 수정
  .idea/compiler.xml
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
Labels: refactor

#72 test : members 테스트 코드 추가
  src/test/java/com/clean/cleanroom/members/controller/MembersAddressControllerTest.java
  src/test/java/com/clean/cleanroom/members/controller/MembersControllerTest.java
  src/test/java/com/clean/cleanroom/members/controller/MembersLoginAndLogoutControllerTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersAddressDelResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersAddressRequestDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersAddressResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersGetProfileResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersLoginRequestDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersLoginResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersLogoutResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersProfileResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersRequestDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersSignupResponseDtoTest.java
  src/test/java/com/clean/cleanroom/members/dto/MembersUpdateProfileRequestDtoTest.java
Labels: refactor

#74 refactor : 필터 여러번의 파싱 문제 수정
  src/main/java/com/clean/cleanroom/config/WebConfig.java
  src/main/java/com/clean/cleanroom/exception/CustomException.java
  src/main/java/com/clean/cleanroom/filter/JwtAuthenticationFilter.java
  src/main/java/com/clean/cleanroom/util/JwtUtil.java
Labels: refactor

#75 refactor : login 로직 비동기 처리 추가
  src/main/java/com/clean/cleanroom/config/AsyncConfig.java
  src/main/java/com/clean/cleanroom/jwt/service/TokenService.java
  src/main/java/com/clean/cleanroom/members/service/MembersLoginService.java
Labels: refactor

#76 Refactor : commission Status추가
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/MyCommissionResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateResponseDto.java
Labels: refactor

#79 refactor : 필드명 수정
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCancelResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionUpdateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/MyCommissionResponseDto.java
Labels: refactor

#80 refactor : 필드명 수정
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateResponseDto.java
Labels: refactor

#82 feat : image upload API add
  .idea/compiler.xml
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionFileResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/resources/application.properties
Labels: feat

#86 Feat/upload
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/resources/application.properties
Labels: feat

#87 Feat/upload get
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionFileGetResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/resources/application.properties
Labels: feat

#88 feat : uploadGet API change
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
Labels: feat

#90 Refactor : commission 청소의뢰 단건조회 API 수정
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmDetailResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
Labels: refactor

#91 feat : 견적 단건 조회 기능 추가
  src/main/java/com/clean/cleanroom/estimate/controller/EstimateController.java
  src/main/java/com/clean/cleanroom/estimate/dto/EstimateDetailResponseDto.java
  src/main/java/com/clean/cleanroom/estimate/service/EstimateService.java
Labels: feat

#92 refactor : 로컬환경에서도 로그를 파일로 저장하도록 수정
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: refactor

#93 refactor : 서버에서 INFO레벨 이상의 로그들이 파일로 저장되도록 수정
  src/main/resources/logback-spring.xml
Labels: refactor

#94 refactor : 청소의뢰 단건조회에 주소ID추가
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
Labels: refactor

#97 Refactor : 성능 테스트 개선 트랜잭션 처리
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
Labels: refactor

#98 Refactor : 성능테스트 개선 캐싱적용
  build.gradle
  src/main/java/com/clean/cleanroom/CleanRoomApplication.java
  src/main/java/com/clean/cleanroom/commission/repository/CommissionRepository.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
Labels: remove

#99 test : 테스트 커버리지 리포팅을 위한 JaCoCo 추가
  build.gradle
Labels: test

#100 Refactor : 성능테스트 개선 캐싱롤백
  build.gradle
  src/main/java/com/clean/cleanroom/CleanRoomApplication.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionConfirmListResponseDto.java
  src/main/java/com/clean/cleanroom/commission/repository/CommissionRepository.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
Labels: refactor

#101 test : 비즈니스 로직에 맞춰 테스트 코드 수정
  .idea/compiler.xml
  src/test/java/com/clean/cleanroom/commission/controller/CommissionControllerTest.java
  src/test/java/com/clean/cleanroom/commission/service/CommissionServiceTest.java
  src/test/java/com/clean/cleanroom/estimate/controller/EstimateControllerTest.java
  src/test/java/com/clean/cleanroom/estimate/dto/EstimateDetailResponseDtoTest.java
  src/test/java/com/clean/cleanroom/estimate/service/EstimateServiceTest.java
  src/test/java/com/clean/cleanroom/filter/JwtAuthenticationFilterTest.java
Labels: test

#102 refactor : 내 청소의뢰 내역 조회 N+1문제 해결
  src/main/java/com/clean/cleanroom/commission/entity/Commission.java
  src/main/java/com/clean/cleanroom/commission/repository/CommissionRepository.java
Labels: refactor

#103 refactor : 시간복잡도 성능개선
  src/main/java/com/clean/cleanroom/commission/controller/CommissionController.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCancelResponseDto.java
  src/main/java/com/clean/cleanroom/commission/dto/CommissionCreateResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
Labels: refactor

#106 Feat/social login
  .idea/dataSources.xml
  src/main/java/com/clean/cleanroom/members/service/KakaoLoginService.java
  src/main/resources/application.properties
Labels: refactor

#107 refactor : 성능 테스트 개선 네이티브 쿼리 사용으로 공간복잡도 확보
  src/main/java/com/clean/cleanroom/commission/dto/MyCommissionResponseDto.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/members/dto/MemberIdAndNickDto.java
  src/main/java/com/clean/cleanroom/members/repository/MembersRepository.java
Labels: refactor

#108 refactor : 성능 테스트 개선 내 청소의뢰 내역 전체조회에 캐싱적용
  build.gradle
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/config/CacheConfig.java
  src/test/java/com/clean/cleanroom/commission/service/CommissionServiceTest.java
Labels: refactor

#109 refactor : 스프링 부트에 캐싱적용 어노테이션 추가
  src/main/java/com/clean/cleanroom/CleanRoomApplication.java
  src/main/java/com/clean/cleanroom/commission/service/CommissionService.java
  src/main/java/com/clean/cleanroom/config/CacheConfig.java
Labels: refactor

#110 refactor : 공간복잡도 측정 후 개선
  src/main/java/com/clean/cleanroom/config/SecurityConfig.java
  src/main/java/com/clean/cleanroom/exception/ErrorMsg.java
  src/main/java/com/clean/cleanroom/members/dto/MembersEmailAndPasswordDto.java
  src/main/java/com/clean/cleanroom/members/dto/MembersLoginResponseDto.java
  src/main/java/com/clean/cleanroom/members/entity/Members.java
  src/main/java/com/clean/cleanroom/members/repository/MembersRepository.java
  src/main/java/com/clean/cleanroom/members/service/MembersLoginService.java
Labels: refactor
